### ISSUE TITLE
Log key name typo

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-receipt-rrm#16]
https://github.com/ONSdigital/sdx-receipt-rrm/blob/958100e03028da4d3a2a074103dab43ecf36e498/app/response_processor.py#L77

Unintentional change to stats_code. Monitoring is failing because it expected status_code. Really should be updated to status instead of status_code anyway, but stats_code is definitely wrong.

**Comment by JamesGardiner** [comment]
Closed in #19
