### ISSUE TITLE
Queue env var inconsistently named

### ISSUE THREAD

**Issue by eldeal** [ONSdigital/sdx-receipt-rrm#4]
https://github.com/ONSdigital/sdx-receipt-rrm/blob/6964ccef6a7e69e1678795c68ab95a6db667550b/app/settings.py#L18

Should be RABBIT_QUEUE to be consistent with other repos, or a more descriptive name - definitely no MQ though.

**Comment by collisdigital** [comment]
Same as other issue in other repo, no longer required.
